# Generated by Django 5.1.1 on 2024-12-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0047_rename_currencytype_accountbank_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnavigation',
            name='PageName_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='page-english'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='PageName_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='page-english'),
        ),
        migrations.AlterField(
            model_name='historicalnavigation',
            name='PageName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pagína-español'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='PageName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pagína-español'),
        ),
    ]
