# Generated by Django 4.2 on 2024-12-20 22:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0048_historicalnavigation_pagename_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='Content_en',
            field=ckeditor.fields.RichTextField(default='Pendiente', verbose_name='Content-english'),
        ),
        migrations.AddField(
            model_name='historicalnews',
            name='Title_en',
            field=models.CharField(default='Pendiente', max_length=255, verbose_name='Title-english'),
        ),
        migrations.AddField(
            model_name='news',
            name='Content_en',
            field=ckeditor.fields.RichTextField(default='Pendiente', verbose_name='Content-english'),
        ),
        migrations.AddField(
            model_name='news',
            name='Title_en',
            field=models.CharField(default='Pendiente', max_length=255, verbose_name='Title-english'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido-español'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Titulo-español'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido-español'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Titulo-español'),
        ),
    ]
