# Generated by Django 4.2 on 2024-12-20 22:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0049_historicalnews_content_en_historicalnews_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnews',
            name='Content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content-english'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Title_en',
            field=models.CharField(max_length=255, verbose_name='Title-english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content-english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title_en',
            field=models.CharField(max_length=255, verbose_name='Title-english'),
        ),
    ]
