# Generated by Django 4.2 on 2024-12-21 19:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0050_alter_historicalnews_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educations',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='historicaleducations',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicaleducations',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content-english'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title-english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content-english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title-english'),
        ),
    ]
