# Generated by Django 4.2 on 2024-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0052_educations_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Content_mission_en',
            field=models.TextField(blank=True, verbose_name='Contenido Misión'),
        ),
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Content_motivation_en',
            field=models.TextField(blank=True, verbose_name='Contenido Motivación'),
        ),
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Content_objetive_en',
            field=models.TextField(blank=True, verbose_name='Contenido Objetivo'),
        ),
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Title_mission_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Misión'),
        ),
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Title_motivation_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Motivación'),
        ),
        migrations.AddField(
            model_name='historicalmissionvalues',
            name='Title_objetive_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Objetivo'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Content_mission_en',
            field=models.TextField(blank=True, verbose_name='Contenido Misión'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Content_motivation_en',
            field=models.TextField(blank=True, verbose_name='Contenido Motivación'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Content_objetive_en',
            field=models.TextField(blank=True, verbose_name='Contenido Objetivo'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Title_mission_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Misión'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Title_motivation_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Motivación'),
        ),
        migrations.AddField(
            model_name='missionvalues',
            name='Title_objetive_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo Objetivo'),
        ),
    ]
