# Generated by Django 4.2 on 2024-12-21 19:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0053_historicalmissionvalues_content_mission_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content-en'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='title-en'),
        ),
        migrations.AlterField(
            model_name='historicaleducations',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content-en'),
        ),
        migrations.AlterField(
            model_name='historicaleducations',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='title-en'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_mission_en',
            field=models.TextField(blank=True, verbose_name='Mission_Content-en'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_motivation_en',
            field=models.TextField(blank=True, verbose_name='Content-Motivation-en'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_objetive',
            field=models.TextField(verbose_name='Objetive_Content-en'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Title_mission_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mission_Title-en'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Title_motivation_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivation_Title-en'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content-en'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title-en'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_mission_en',
            field=models.TextField(blank=True, verbose_name='Mission_Content-en'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_motivation_en',
            field=models.TextField(blank=True, verbose_name='Content-Motivation-en'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_objetive',
            field=models.TextField(verbose_name='Objetive_Content-en'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Title_mission_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mission_Title-en'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Title_motivation_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivation_Title-en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content-en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title-en'),
        ),
    ]
