# Generated by Django 4.2 on 2024-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0054_alter_educations_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwhoweare',
            name='Content_en',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='historicalwhoweare',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='Content_en',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='Title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo'),
        ),
    ]
