# Generated by Django 4.2 on 2024-12-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0055_historicalwhoweare_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Direccion del evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo del evento'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='Address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Direccion del evento'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='Event_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo del evento'),
        ),
    ]
