# Generated by Django 4.2 on 2025-01-08 15:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FuturoCiertoContent', '0057_causes_cause_en_causes_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalwhatOurDonorsSay',
            fields=[
                ('DonorsSayID', models.IntegerField(blank=True, db_index=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo')),
                ('Comment1', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 1')),
                ('Comment2', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 2')),
                ('Comment3', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 3')),
                ('Comment1_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 1')),
                ('Comment2_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 2')),
                ('Comment3_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 3')),
                ('Image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen ')),
                ('TextAlt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Reflección',
                'verbose_name_plural': 'historical Reflección',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='whatOurDonorsSay',
            fields=[
                ('DonorsSayID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo')),
                ('Comment1', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 1')),
                ('Comment2', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 2')),
                ('Comment3', ckeditor.fields.RichTextField(default='', max_length=450, verbose_name='Comentario Donante 3')),
                ('Comment1_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 1')),
                ('Comment2_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 2')),
                ('Comment3_en', ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Donator Comment 3')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Imagen ')),
                ('TextAlt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reflección',
                'verbose_name_plural': 'Reflección',
            },
        ),
        migrations.RemoveField(
            model_name='historicalreflectionbyjose',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='reflectionByJose',
        ),
        migrations.AlterField(
            model_name='historicalnavigation',
            name='Url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='Url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='HistoricalreflectionByJose',
        ),
    ]
