# Generated by Django 4.2 on 2025-03-18 21:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0058_historicalwhatourdonorssay_whatourdonorssay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalwhatourdonorssay',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Comentarios Donantes', 'verbose_name_plural': 'historical Comentarios Donantes'},
        ),
        migrations.AlterModelOptions(
            name='whatourdonorssay',
            options={'verbose_name': 'Comentarios Donantes', 'verbose_name_plural': 'Comentarios Donantes'},
        ),
        migrations.AlterField(
            model_name='historicalwhoweare',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='Content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
    ]
