name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/futurociertoapi:latest

      - name: Configure AWS Permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USER}}
          key: ${{secrets.AWS_SSH_KEY}}
          port: 22
          script: |
            echo "🔧 Configurando permisos en el servidor..."
            sudo mkdir -p /home/ec2-user/media
            sudo mkdir -p /home/ec2-user/staticfiles
            sudo chown -R 0:0 /home/ec2-user/media
            sudo chmod -R 775 /home/ec2-user/media
            sudo chown -R 0:0 /home/ec2-user/staticfiles
            sudo chmod -R 775 /home/ec2-user/staticfiles
            sudo semanage fcontext -a -t container_file_t "/home/ec2-user/media(/.*)?" || true
            sudo restorecon -Rv /home/ec2-user/media/

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USER}}
          key: ${{secrets.AWS_SSH_KEY}}
          port: 22
          script: |
            echo "🚀 Iniciando despliegue..."
            echo "Deteniendo contenedor actual..."
            docker stop futurocierto_container || true
            docker rm futurocierto_container || true
            
            echo "Extrayendo imagen actualizada..."
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/futurociertoapi:latest
            
            echo "Ejecutando nuevo contenedor..."
            docker run -d \
              -p 8000:8000 \
              --name futurocierto_container \
              -v /home/ec2-user/media:/app/media:rw \
              -v /home/ec2-user/staticfiles:/app/staticfiles:rw \
              -e FILE_UPLOAD_PERMISSIONS=0o664 \
              -e FILE_UPLOAD_DIRECTORY_PERMISSIONS=0o775 \
              ${{secrets.DOCKERHUB_USERNAME}}/futurociertoapi:latest

            echo "⏳ Esperando inicialización..."
            sleep 15

            echo "📌 Configurando la aplicación..."
            docker exec futurocierto_container python manage.py collectstatic --noinput
            docker exec futurocierto_container python manage.py migrate --noinput

            echo "✅ Despliegue completado exitosamente!"